name: React Frontend Build

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Check Node and NPM
        run: |
          node --version
          npm --version

      - name: Install dependencies
        run: npm ci

      - name: Build React application
        run: npm run build
