name: React Frontend Build

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:

  build:
    runs-on: self-hosted

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Check Node and NPM
        run: |
          node --version
          npm --version

      - name: Install dependencies
        run: npm ci

      - name: Build React application
        run: npm run build

      - name: Upload frontend build
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build
          path: build/


  deploy:
    needs: build
    runs-on: self-hosted

    steps:
      - name: Download frontend build
        uses: actions/download-artifact@v4
        with:
          name: frontend-build
          path: build

      - name: Deploy to Nginx
        run: |
          sudo rm -rf /var/www/html/*
          sudo cp -r build/* /var/www/html/
          sudo systemctl reload nginx

      - name: Verify deployment
        run: |
          echo "Files deployed:"
          ls -la /var/www/html
          echo "Testing Nginx:"
          curl -I http://localhost
